version: '3.9'

services:
  fastapi-executor:
    build: .
    ports:
      - "8000:8000"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
